version: '3.7'

services:
      
  sd.rabbitmq:
    image: rabbitmq:3-management
    container_name: sdrabbitmq
    ports:
      - "15672:15672"
      - "5671:5671"
      - "5672:5672"
    environment: 
      DEFAULT_PASS: guest
      DEFAULT_USER: guest

  sd.database:
    image: mcr.microsoft.com/mssql/server:2017-latest
    container_name: sdSqlServer
    ports:
    - "11433:1433"
    environment: 
      MSSQL_SA_PASSWORD: ea!@#12345
      MSSQL_PID: Developer
      ACCEPT_EULA: 'Y'
   

  sd.mongodb:
    image: mongo
    container_name: sdmongodb
    ports:
      - "27017:27017"

  sd.redis:
    image: redis
    container_name: sdredis
    command: redis-server --requirepass ea!@#12345
    ports:
      - "6379:6379"