CREATE TABLE [dbo].[Usuario]
(
	[Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY, 
    [Nome] NVARCHAR(100) NOT NULL, 
    [Email] NVARCHAR(100) NOT NULL, 
    [CPF] NVARCHAR(14) NOT NULL, 
    [Celular] NVARCHAR(14) NOT NULL, 
    [Senha] VARCHAR(500) NOT NULL, 
    [Tipo] INT NOT NULL, 
    [DataCadastro] DATETIME NOT NULL, 
    [Status] INT NOT NULL
)
